//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/FogControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FogControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FogControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FogControl"",
    ""maps"": [
        {
            ""name"": ""ControlFog"",
            ""id"": ""c4f0725e-45b8-4c25-9be2-591d919f8597"",
            ""actions"": [
                {
                    ""name"": ""FogToggle"",
                    ""type"": ""Button"",
                    ""id"": ""3eae5bfa-174e-48a7-a34a-b40eadd410c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0dfc5cfb-84c3-4d51-9555-72546adb5118"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FogToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlFog
        m_ControlFog = asset.FindActionMap("ControlFog", throwIfNotFound: true);
        m_ControlFog_FogToggle = m_ControlFog.FindAction("FogToggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlFog
    private readonly InputActionMap m_ControlFog;
    private List<IControlFogActions> m_ControlFogActionsCallbackInterfaces = new List<IControlFogActions>();
    private readonly InputAction m_ControlFog_FogToggle;
    public struct ControlFogActions
    {
        private @FogControl m_Wrapper;
        public ControlFogActions(@FogControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @FogToggle => m_Wrapper.m_ControlFog_FogToggle;
        public InputActionMap Get() { return m_Wrapper.m_ControlFog; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlFogActions set) { return set.Get(); }
        public void AddCallbacks(IControlFogActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlFogActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlFogActionsCallbackInterfaces.Add(instance);
            @FogToggle.started += instance.OnFogToggle;
            @FogToggle.performed += instance.OnFogToggle;
            @FogToggle.canceled += instance.OnFogToggle;
        }

        private void UnregisterCallbacks(IControlFogActions instance)
        {
            @FogToggle.started -= instance.OnFogToggle;
            @FogToggle.performed -= instance.OnFogToggle;
            @FogToggle.canceled -= instance.OnFogToggle;
        }

        public void RemoveCallbacks(IControlFogActions instance)
        {
            if (m_Wrapper.m_ControlFogActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlFogActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlFogActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlFogActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlFogActions @ControlFog => new ControlFogActions(this);
    public interface IControlFogActions
    {
        void OnFogToggle(InputAction.CallbackContext context);
    }
}
